feat(load test data):  Add a pattern/mechanism to seed the database with data for dev/test purposes (#26)
* adding random seed data generation

* adding jsonplaceholder handler

* correcting lambada handler file name

* modifying response to including afsiled

* modifying response to including afsiled

* exporting seedData

* force update the seeddata function

* force update the seeddata function

* exporting seed data module

* exporting seed data module

* defining time stamp function

* adding tableName env variable

* adding serverless-scripts plugin

* adding lamdba invoke command

* functional

* proper error handling

* package not needed

* Remove commented out line

---------

Co-authored-by: Ishmeal Baawuah <ibaawuah@Ishmeals-MBP.fios-router.home>
Co-authored-by: Ishmeal Baawuah <ibaawuah@ip-10-232-62-129.ec2.internal>

diff --git a/src/services/database/serverless.yml b/src/services/database/serverless.yml
--- a/src/services/database/serverless.yml
+++ b/src/services/database/serverless.yml
@@ -10,6 +10,7 @@ plugins:
   - "@stratiformdigital/serverless-s3-security-helper"
   - "@stratiformdigital/serverless-iam-helper"
   - serverless-bundle
+  - serverless-plugin-scripts
 
 provider:
   name: aws
@@ -37,22 +38,36 @@ provider:
 
 custom:
   project: ${env:PROJECT}
-  fileHash: ${file(./items.json)}
+  referenceDataHash: ${file(./src/reference/items.json)}
   serverlessTerminationProtection:
     stages: # Apply CloudFormation termination protection for these stages
       - master
       - val
       - production
   tableName: ${self:service}-${sls:stage}-table
-
-parameters:
-  fileHash:
-    Type: String
-    Default: ""
+  scripts:
+    commands:
+      seed: |
+        set -e
+        echo 'Loading test data...'
+        call=`aws lambda invoke --region ${self:provider.region} --function-name ${self:service}-${sls:stage}-testDataLoader --invocation-type RequestResponse --payload $(base64 ./src/test/items.json) --log Tail /dev/null`
+        error=`echo $call | jq 'select(.FunctionError != null)'`
+        if [ "$error" != "null" -a -n "$error" ]; then
+          echo "An error occured while loading test data.  Error below"
+          echo `echo $call | jq -r '.LogResult'` | base64 --decode
+          exit 1
+        fi
 
 functions:
   seeddatabase:
     handler: handlers/seeddatabase.handler
+    environment:
+      region: ${self:provider.region}
+  testDataLoader:
+    handler: handlers/testDataLoader.handler
+    environment:
+      region: ${self:provider.region}
+      tableName: !Ref Table
 
 resources:
   Resources:
@@ -81,4 +96,4 @@ resources:
           Fn::GetAtt: [SeeddatabaseLambdaFunction, "Arn"]
         DynamoTableName:
           Ref: Table
-        FILE_HASH: ${self:custom.fileHash}
+        Trigger: ${self:custom.referenceDataHash}
